// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEcf_s3mu5Ah27xqGhVo7m9y_Vay_u4tU',
    appId: '1:645599191590:web:bc6c175eb980d27d80fce7',
    messagingSenderId: '645599191590',
    projectId: 'ev-charging-paltform',
    authDomain: 'ev-charging-paltform.firebaseapp.com',
    databaseURL: 'https://ev-charging-paltform-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ev-charging-paltform.firebasestorage.app',
    measurementId: 'G-KLS28PG2SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnO7e754kVBLC1V-t4QXiIceBI5_HKOrg',
    appId: '1:645599191590:android:bae8a2a3821fe3f380fce7',
    messagingSenderId: '645599191590',
    projectId: 'ev-charging-paltform',
    databaseURL: 'https://ev-charging-paltform-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ev-charging-paltform.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEcf_s3mu5Ah27xqGhVo7m9y_Vay_u4tU',
    appId: '1:645599191590:web:5291f4205ebe158580fce7',
    messagingSenderId: '645599191590',
    projectId: 'ev-charging-paltform',
    authDomain: 'ev-charging-paltform.firebaseapp.com',
    databaseURL: 'https://ev-charging-paltform-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ev-charging-paltform.firebasestorage.app',
    measurementId: 'G-W8CFCYCFN3',
  );
}
